sudo: false
language: python
python:
    - "3.12"
before_install:
- deactivate
- pyenv global 3.12
- python3 -m pip install -U tox --user
install:
- python3 -m tox --notest
script: python3 -m tox
notifications:
  email: false
